ARG from
FROM $from

COPY etc/ /etc/
COPY usr/ /usr/

# kernel
RUN mkdir -p /boot/dtb && \
    dnf -y remove \
        kernel \
        kernel-core \
        kernel-modules \
        kernel-modules-core && \
    dnf -y copr enable -y gmanka/test && \
    dnf -y install --from-repo='copr:copr.fedorainfracloud.org:gmanka:test' 'kernel-6.16.0-0.rodriguezst.sm8150.*' && \
    rm -r /boot/dtb

RUN dnf -y install \
    xiaomi-nabu-firmware \
    xiaomi-nabu-audio \
    qbootctl

RUN systemctl enable qbootctl.service

# cleanup
RUN rm -rf /var/log/* && dnf clean all

RUN bootc container lint
