ARG from
FROM $from

COPY etc/ /etc/
COPY usr/ /usr/

RUN dnf -y copr enable gmanka/test
RUN mkdir -p /boot/dtb && \
    dnf -y remove \
        kernel \
        kernel-core \
        kernel-modules \
        kernel-modules-core && \
    dnf -y install \
        kernel-6.14.0-4.sm8150.fc42 \
        xiaomi-nabu-firmware \
        xiaomi-nabu-audio \
        qbootctl \
        btop && \
    systemctl enable qbootctl.service && \
    dnf clean all && \
    bootc container lint
