ARG from
FROM $from

COPY etc/ /etc/

# kernel
RUN mkdir -p /boot/dtb && \
    dnf -y remove \
        kernel \
        kernel-core \
        kernel-modules \
        kernel-modules-core && \
    dnf -y install kernel && \
    dnf -y copr enable gmanka/test && \
    dnf -y install --from-repo='copr:copr.fedorainfracloud.org:gmanka:test' 'kernel-6.16.0-3.rodriguezst.sm8150.*' && \
    rm -r /boot/dtb

RUN dnf -y install \
    xiaomi-nabu-firmware \
    alsa-ucm-conf-sm8150 \
    ath10k-shutdown \
    tqftpserv \
    qbootctl \
    rmtfs \
    qrtr

RUN systemctl enable \
    tqftpserv.service \
    rmtfs.service \
    qbootctl.service

# cleanup
RUN rm -rf /var/log/* && dnf clean all

RUN bootc container lint
