on:
  workflow_call:
    inputs:
      device:
        required: true
        type: string
      from_tag:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      from_tag:
        type: choice
        description: 'fedora branch'
        required: true
        options:
          - '42'
          - '43'
          - 'rawhide'
        default: '42'
      device:
        type: choice
        description: 'device name'
        required: true
        options:
          - nothing-spacewar
          - oneplus-sdm845
          - xiaomi-nabu
          - xiaomi-pipa
          - xunlong-orangepi3-lts

jobs:
  device:
    permissions:
      packages: write
    secrets: inherit
    uses: ./.github/workflows/helper-build-container.yml
    with:
      from_tag: ${{ inputs.from_tag }}
      from_image: base
      target_image: ${{ inputs.device }}-base
      context: devices/${{ inputs.device }}/container
      rechunk: false

  desktops:
    needs: device
    permissions:
      packages: write
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        desktop: [gnome-desktop, gnome-mobile, plasma-desktop, plasma-mobile, phosh]
    uses: ./.github/workflows/helper-build-container.yml
    with:
      from_tag: ${{ inputs.from_tag }}
      from_image: ${{ inputs.device }}-base
      target_image: ${{ inputs.device }}-${{ matrix.desktop }}
      context: desktops/${{ matrix.desktop }}
      rechunk: true
